### ISSUE TITLE
单选进入剪切页面报错

### ISSUE THREAD

**Issue by DuShuYuan** [CysionLiu/ImagePicker#22]
多选没问题，查看大图也不行
大图显示出来了，然后直接崩溃

日志：

 java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.locojoy.libros_books.BookApplication$1)
        at android.os.Parcel.writeSerializable(Parcel.java:1714)
        at android.os.Parcel.writeValue(Parcel.java:1662)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1583)
        at android.os.Bundle.writeToParcel(Bundle.java:1233)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3986)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.io.NotSerializableException: com.locojoy.libros_books.BookApplication
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
        at android.os.Parcel.writeSerializable(Parcel.java:1709)
        at android.os.Parcel.writeValue(Parcel.java:1662) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:875) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1583) 
        at android.os.Bundle.writeToParcel(Bundle.java:1233) 
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3986) 
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144) 
        at android.os.Handler.handleCallback(Handler.java:891) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by DuShuYuan** [comment]
不知道为啥会报序列化的问题

**Comment by DuShuYuan** [comment]
错误代码：
imagePicker.setImageLoader(new ImageLoader() {
            @Override
            public void displayImage(Activity activity, String path, ImageView imageView, int width, int height) {
                。。。
            }

            @Override
            public void displayImagePreview(Activity activity, String path, ImageView imageView, int width, int height) {
。。。
            }

            @Override
            public void clearMemoryCache() {

            }
        }); 

解决问题：
imagePicker.setImageLoader(new GlideImageLoader());

public class GlideImageLoader implements ImageLoader {
    @Override
    public void displayImage(Activity activity, String path, ImageView imageView, int width, int height) {
       。。。
    }

    @Override
    public void displayImagePreview(Activity activity, String path, ImageView imageView, int width, int height) {
        。。。
    }

    @Override
    public void clearMemoryCache() {

    }
}
