### ISSUE TITLE
每点一次拍照，相册就生成一张无大小的图片，选择剪切还崩溃

### ISSUE THREAD

**Issue by DuShuYuan** [CysionLiu/ImagePicker#60]
希望不要在点击拍照时生成picture文件夹，不拍照会生成无用文件，拍照会生成所拍的照片，DCIM文件夹里也有拍的照片，重复了

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
	at com.lzy.imagepicker.view.CropImageView.saveOutput(CropImageView.java:506)
	at com.lzy.imagepicker.view.CropImageView.access$000(CropImageView.java:38)
	at com.lzy.imagepicker.view.CropImageView$1.run(CropImageView.java:484)

**Comment by CysionLiu** [comment]
临时建议，使用FreeCrop模式
