### ISSUE TITLE
IOException

### ISSUE THREAD

**Issue by youarenowhere** [CysionLiu/ImagePicker#64]
com.cysion:ImagePicker:1.2.0.x
小米5s plus
进入相册选择图片，可以正常使用，但是报如下异常
ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
` java.io.IOException: Invalid marker: 89
        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
        at android.media.ExifInterface.<init>(ExifInterface.java:1112)
        at com.lzy.imagepicker.util.BitmapUtil.getBitmapDegree(BitmapUtil.java:26)
        at com.lzy.imagepicker.ui.ImageCropActivity.onCreate(ImageCropActivity.java:64)
        at android.app.Activity.performCreate(Activity.java:6875)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2694)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6379)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)`

**Comment by CysionLiu** [comment]
文件格式不对或者文件已损坏。这里try-catch了。特殊格式的图片信息解析，本库暂不支持
