### ISSUE TITLE
VIVO闪退

### ISSUE THREAD

**Issue by VectorWen** [CysionLiu/ImagePicker#80]
java.lang.String java.io.File.getName()' on a null object reference
	at com.lzy.imagepicker.ImageDataSource.a(ImageDataSource.java:29)
	at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:1)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:5)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:1)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:3)
	at androidx.loader.content.Loader.deliverResult(Loader.java:2)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:7)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:1)
	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:8)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:1)
	at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:3)
	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7222)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876

**Comment by VectorWen** [comment]
项目里面源码还不是最新的。咋整哦。

**Comment by VectorWen** [comment]
下面代码在master 无法找到。其他分支也没有    
private final String[] IMAGE_PROJECTION_Q = {
            MediaStore.Images.Media.DISPLAY_NAME,
            MediaStore.Images.Media.RELATIVE_PATH,
            MediaStore.Images.Media.SIZE,
            MediaStore.Images.Media.WIDTH,
            MediaStore.Images.Media.HEIGHT,
            MediaStore.Images.Media.MIME_TYPE,
            MediaStore.Images.Media.DATE_ADDED,
            MediaStore.Images.Media._ID
    };
